import { createHash } from 'node:crypto';

import type { QuoteInput } from '../../src/modules/pricing/pricing.facade';

/**
 * A deterministic set of quote inputs used to compare the batched pricing loader against the
 * per-line one it replaced.
 *
 * Deterministic is the whole point: a randomised set that differs between runs cannot be compared
 * against anything. The "randomised ~200 combinations" the brief asks for is produced by a SEEDED
 * generator, so the same 200 combinations are replayed every time.
 */

/** mulberry32 — small, fast, and identical across Node versions. */
function seededRandom(seed: number): () => number {
  let state = seed >>> 0;

  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export interface QuoteCase {
  name: string;
  input: QuoteInput;
}

const PINCODES = ['560001', '400001', '600001', '110001', '700001'];
const CHANNELS = ['WEB', 'APP'] as const;

/**
 * Every case is priced at ONE frozen instant.
 *
 * Without this the fixture is unreplayable: coupons and discount rules have date windows, and a
 * recording taken on one side of a window boundary disagrees with a replay taken on the other —
 * which looks exactly like a pricing regression and is not one.
 */
export const FROZEN_NOW = new Date('2026-06-15T12:00:00.000Z');

/**
 * Builds the case list from real catalog slugs. Sorted and index-numbered so the order is stable
 * regardless of the order the database returned the products in.
 */
export function buildQuoteCases(slugs: string[], count = 200): QuoteCase[] {
  const ordered = [...slugs].sort();
  if (ordered.length === 0) return [];

  const random = seededRandom(20_260_921);
  const cases: QuoteCase[] = [];

  // Every single product on its own: the case most of the site actually hits.
  for (const slug of ordered) {
    cases.push({
      name: `single:${slug}`,
      input: { items: [{ slug, qty: 1 }], channel: 'WEB', now: FROZEN_NOW },
    });
  }

  // Then multi-line carts of varying size, quantity, pincode and channel.
  while (cases.length < count) {
    const lineCount = 1 + Math.floor(random() * 8);
    const items: QuoteInput['items'] = [];

    for (let index = 0; index < lineCount; index += 1) {
      items.push({
        slug: ordered[Math.floor(random() * ordered.length)],
        qty: 1 + Math.floor(random() * 6),
      });
    }

    cases.push({
      name: `cart:${cases.length}`,
      input: {
        items,
        pincode: PINCODES[Math.floor(random() * PINCODES.length)],
        channel: CHANNELS[Math.floor(random() * CHANNELS.length)],
        now: FROZEN_NOW,
      },
    });
  }

  return cases.slice(0, count);
}

/**
 * cuids are regenerated by every seed, so they cannot appear in a committed fixture.
 *
 * They must be replaced wherever they occur, not only when a string IS one, and not only at a word
 * boundary. Price components carry codes like `ADJ_cmubfxfbk07gfr9w8vgp5mhkj` — the `_` is a word
 * character, so a `\b`-anchored pattern misses it. An earlier version matched only a whole-string
 * cuid, which made 83 of 200 cases look like a pricing regression when every amount was identical.
 * That mistake is why Prompt B1 abandoned the fixture.
 */
const CUID_ANYWHERE = /c[a-z0-9]{24}(?![a-z0-9])/g;

function normaliseIds(value: unknown): unknown {
  if (typeof value === 'string') return value.replace(CUID_ANYWHERE, '<id>');
  if (Array.isArray(value)) return value.map(normaliseIds);

  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([key, entry]) => [
        key,
        normaliseIds(entry),
      ]),
    );
  }

  return value;
}

/**
 * A stable fingerprint of a breakdown, comparable across database seeds.
 *
 * `calculatedAt` is the wall clock. `contextHash` is a digest over raw ids, so it can never match
 * across seeds; it is asserted separately for presence, determinism and shape.
 */
export function fingerprint(breakdown: Record<string, unknown>): string {
  const { calculatedAt: _calculatedAt, contextHash: _contextHash, ...stable } = breakdown;

  return createHash('sha256').update(JSON.stringify(normaliseIds(stable))).digest('hex');
}
